name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

env:
  IMAGE_TAG: dev-1
  DOCKERHUB_REPO: awdfaf/be-meeting
  GITHUB_SSH_PRIVATE_KEY: ${{ secrets.GITHUB_SSH_PRIVATE_KEY }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker build -t $DOCKERHUB_REPO:${{ env.IMAGE_TAG }} .
        docker push $DOCKERHUB_REPO:${{ env.IMAGE_TAG }}

    - name: Update helm chart and push to repository
      env:
        PRIVATE_KEY: ${{ secrets.GITHUB_SSH_PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config user.email "awdfaf@kakao.com"
        git config user.name "awdfaf"
        sed -i "s/tag:.*/tag: ${{ env.IMAGE_TAG }}/g" helm-charts/values.yaml
        git add helm-charts/values.yaml
        git commit -m "Update helm chart with new image tag"
        git push

